--  FILTRAR DATAS

WITH DATE_PED AS (SELECT DISTINCT ID_PEDIDO
                          FROM PEDID
                           WHERE
                            PEDDTBAIXA BETWEEN
                             DATEADD(MONTH, -11, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 1) AND 'YESTERDAY' OR  PEDDTBAIXA BETWEEN DATEADD(MONTH, -11,DATEADD(YEAR, -1, CURRENT_DATE) - EXTRACT(DAY FROM CURRENT_DATE) + 1) AND DATEADD(YEAR, -1, CURRENT_DATE)),

--  FILTRA CFOPS DE VENDA  

FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','R','SR')),

 CLI AS (SELECT CLICODIGO,GCLCODIGO FROM CLIEN WHERE CLICLIENTE='S'),

-- PEDIDOS

PED AS (SELECT P.ID_PEDIDO,
                PEDDTBAIXA,
                 P.CLICODIGO,
                  GCLCODIGO GRUPO
                   FROM PEDID P
                    INNER JOIN DATE_PED DT ON P.ID_PEDIDO=DT.ID_PEDIDO
                     LEFT JOIN CLI C ON P.CLICODIGO=C.CLICODIGO
                      WHERE  PEDSITPED<>'C' AND PEDLCFINANC IN ('S', 'L','N')),

-- PILARES   

VARILUX AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=57 AND PROTIPO<>'T'),

 KODAK_MF AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=24 AND GR2CODIGO=1),

  KODAK_VS AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=24 AND GR2CODIGO=3),

   CRIZAL_VS AS (SELECT PROCODIGO FROM PRODU WHERE (PRODESCRICAO LIKE '%CRIZAL%')  AND GR1CODIGO=2),      

    MREPRO AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO IN (106,128,135,158,159,189) ),

     MCLIENTE AS (SELECT PROCODIGO FROM PRODU WHERE PROCODIGO IN (SELECT PROCODIGO FROM NGRUPOS WHERE GRCODIGO=162) AND PROTIPO<>'T'), 

      TRANSITIONS AS (SELECT PROCODIGO FROM PRODU WHERE (PRODESCRICAO LIKE '%TGEN8%' OR PRODESCRICAO LIKE '%TRANS%') )


-- SELECT FINAL

SELECT   
 EXTRACT(MONTH  FROM PEDDTBAIXA) MES,
  EXTRACT(YEAR  FROM PEDDTBAIXA) ANO,
   CLICODIGO,
    GRUPO,
CASE 
 WHEN VLX.PROCODIGO IS NOT NULL THEN 'VARILUX'
  WHEN KMF.PROCODIGO IS NOT NULL THEN 'KODAK MF'
   WHEN KVS.PROCODIGO IS NOT NULL THEN 'KODAK VS'
    WHEN CVS.PROCODIGO IS NOT NULL THEN 'CRIZAL VS'
     WHEN MRP.PROCODIGO IS NOT NULL THEN 'MARCAS REPRO'
      WHEN MRCL.PROCODIGO IS NOT NULL THEN 'MARCAS CLIENTE'
       ELSE 'OUTROS' END PILARES,
        IIF(TRS.PROCODIGO IS NOT NULL, 1,0) TRANSITIONS,
         SUM(PDPQTDADE) QTD,
          SUM(PDPUNITLIQUIDO*PDPQTDADE) VRVENDA 


FROM PDPRD PD
 INNER JOIN PED P ON P.ID_PEDIDO=PD.ID_PEDIDO
  INNER JOIN FIS F ON F.FISCODIGO=PD.FISCODIGO
   LEFT JOIN VARILUX VLX ON VLX.PROCODIGO=PD.PROCODIGO
    LEFT JOIN KODAK_MF KMF ON KMF.PROCODIGO=PD.PROCODIGO
     LEFT JOIN KODAK_VS KVS ON KVS.PROCODIGO=PD.PROCODIGO
      LEFT JOIN CRIZAL_VS CVS ON CVS.PROCODIGO=PD.PROCODIGO
       LEFT JOIN MREPRO MRP ON MRP.PROCODIGO=PD.PROCODIGO
        LEFT JOIN MCLIENTE MRCL ON MRCL.PROCODIGO=PD.PROCODIGO
         LEFT JOIN TRANSITIONS TRS ON TRS.PROCODIGO=PD.PROCODIGO
          GROUP BY 1,2,3,4,5,6



