

WITH TBPRECO AS (SELECT TBPCODIGO,TBPDESCRICAO FROM TABPRECO WHERE TBPCODIGO IN (102,202,104,103))

SELECT CLICODIGO,C.TBPCODIGO,TBPDESCRICAO,TBPDESC2 FROM CLITBP C
  INNER JOIN TBPRECO T ON C.TBPCODIGO=T.TBPCODIGO

