
WITH  CLI AS (SELECT DISTINCT C.CLICODIGO,GCLCODIGO,CLIPCDESCPRODU FROM CLIEN C
                       INNER JOIN (SELECT CLICODIGO,E.ZOCODIGO FROM ENDCLI E
                        INNER JOIN (SELECT ZOCODIGO FROM ZONA 
                         WHERE ZOCODIGO IN (20))Z ON 
                          E.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
                           WHERE CLICLIENTE='S'),  
                           
                           TBPRECO AS (SELECT TBPCODIGO,TBPDESCRICAO FROM TABPRECO WHERE TBPCODIGO IN (102,202,104,103,301,302,303,304,305,307,308,313))

SELECT CT.CLICODIGO,
        GCLCODIGO,
          CT.TBPCODIGO,
             CASE 
              WHEN TBPDESCRICAO='VARILUX DIGITAL' THEN 'VARILUX'
               WHEN TBPDESCRICAO='KODAK DIGITAL' THEN 'KODAK MF'
                WHEN TBPDESCRICAO='FAMILIA LA KODAK' THEN 'KODAK VS'
                 WHEN TBPDESCRICAO='FAMILIA LA CRIZAL' THEN 'CRIZAL VS'
                  WHEN TBPDESCRICAO='IMAGEM TRADICIONAL' THEN 'IMAGEM TRAD'
                   WHEN TBPDESCRICAO='IMAGEM DIGITAL' THEN 'IMAGEM DIGI'
                    WHEN TBPDESCRICAO='UZ+ / UZ+ SINGLE' THEN 'UZ+'
                     WHEN TBPDESCRICAO='ACTUALITE' THEN 'ACTUALITE'
                      WHEN TBPDESCRICAO='AVANCE' THEN 'AVANCE'
                       WHEN TBPDESCRICAO='INSIGNE' THEN 'INSIGNE'
                        WHEN TBPDESCRICAO='PRIMO' THEN 'PRIMO'
                         ELSE '' END  TBPDESCRICAO,
                          TBPDESC2 DESCONTO FROM CLITBP CT
                           INNER JOIN CLI C ON C.CLICODIGO=CT.CLICODIGO
                            INNER JOIN TBPRECO T ON CT.TBPCODIGO=T.TBPCODIGO UNION
  
SELECT CLICODIGO,GCLCODIGO,0,'DESCONTO GERAL', CLIPCDESCPRODU DESCONTO FROM CLI  

