
WITH  CLI AS (SELECT DISTINCT C.CLICODIGO,GCLCODIGO,CLIPCDESCPRODU FROM CLIEN C
                       INNER JOIN (SELECT CLICODIGO,E.ZOCODIGO FROM ENDCLI E
                        INNER JOIN (SELECT ZOCODIGO FROM ZONA 
                         WHERE ZOCODIGO IN (20))Z ON 
                          E.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
                           WHERE CLICLIENTE='S'),  
                           
                           TBPRECO AS (SELECT TBPCODIGO,TBPDESCRICAO FROM TABPRECO WHERE TBPCODIGO IN (102,202,104,103))

SELECT CT.CLICODIGO,GCLCODIGO,CT.TBPCODIGO,TBPDESCRICAO,TBPDESC2 DESCONTO FROM CLITBP CT
 INNER JOIN CLI C ON C.CLICODIGO=CT.CLICODIGO
  INNER JOIN TBPRECO T ON CT.TBPCODIGO=T.TBPCODIGO UNION
  
SELECT CLICODIGO,GCLCODIGO,0,'DESCONTO GERAL', CLIPCDESCPRODU DESCONTO FROM CLI  

