WITH  CLI AS (SELECT DISTINCT C.CLICODIGO,GCLCODIGO FROM CLIEN C
                       INNER JOIN (SELECT CLICODIGO,E.ZOCODIGO FROM ENDCLI E
                        INNER JOIN (SELECT ZOCODIGO FROM ZONA 
                         WHERE ZOCODIGO IN (20))Z ON 
                          E.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
                           WHERE CLICLIENTE='S')

SELECT DISTINCT NC.CLICODIGO,
                 GCLCODIGO,
                   NVALORESCLIEN
                  FROM NROTULOSCLIEN NC
                   INNER JOIN CLI C ON NC.CLICODIGO=C.CLICODIGO
                    LEFT JOIN NVALORESCLIEN N ON NC.CLICODIGO=N.CLICODIGO
                    WHERE N.RTCCODIGO=3

